# config context path to "/" by setting an empty string
server:
  contextPath:
  port: 8583

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
#  jpa:
#    hibernate:
#      # possible values: validate | update | create | create-drop
#      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/sso
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG